### ISSUE TITLE
Question: What does the owner field in websites.json do?

### ISSUE THREAD

**Issue by M0on9** [k3rs3d/ringfairy#11]
Could someone explain what the owner field in websites.json does? There isn't any documentation for it, and I don't know why a webring entry would need a owner.

**Comment by k3rs3d** [comment]
It's used to display contact info on the generated site table, with the {{ table_of_sites }} tag! Such as an email address, a "contact" page, or anything. On my webring this is usually a Neocities profile page for most entries. 
So the reason a webring entry might need a unique owner is in case the webring administrator or anyone would like to get any information from the person responsible for that site. Like if there are any issues with the site or anything changes with the webring etc. It's not a required field to add a site to the list, but I wanted to include a lot of optional information about each entry.  
Also, ringfairy will try to make the contact info a hyperlink, for example, linking `mailto:` for an email address etc. 
In the future I would like to possibly make the site table more configurable, so that webring admins can choose which fields are displayed and how they're labeled and everything. But for now it's still using this hard coded table generating tag with the `owner` field from earlier in development.
